enableBlacklist: True
defaultItemDistribution: "2,6,9,6,2"
defaultBingoLinesCompleteForWin: 1
showCurrentlyWinningTeam: True
border:
  enable: True
  overworld-size: 3000
  nether-size: 1000
timer:
  enable: True
  length: 1800
pregenerate-worlds: False
