enable-blacklist: True # 开启黑名单
default-item-distribution: "2,6,9,6,2" # 物品出现比例
default-num-lines-complete-for-win: 1 # 默认完成多少行会获胜
show-currently-winning-team: True # 显示当前获胜团队
notify-other-team-completions: True # 通知其他团队完成情况
prevent-water-spawns: True # 防止水生成
show-all-maps-after-game: True # 在游戏结束后向玩家展示所有队伍的收集情况
give-all-recipes: True # 给出所有物品
freeze-time-on-start: 5 # 开始冷却时间
notify-progress:
  lines:
    - each
  full-card:
    - 10
    - 20
    - 23
  lockout:
    - 5
    - 10
border:
  enable: True # 是否开启世界边界
  overworld-size: 3000 # 主世界边界
  nether-size: 1000 # 下界边界
  override-world-generation: False
timer:
  enable: True
  length: 1800
pregeneration-mode:
  enable: False # 预生成模式
pregame:
  border-radius: 20 # 出生点范围
auto-start:
  min-players: 4 # 自动开启最小人数，至少 4
  max-players-pre-team: 4 #每支队伍最多能容纳的人数，默认为 4，不建议修改
